import 'package:cognivoice/models/message.model.dart';

final List<ChatMessage> chat = [
  ChatMessage(
    id: "",
    audio: "",
    audioUrl: "http://10.128.65.249:3001/audio",
    chatId: "",
    createdAt: "",
    updatedAt: "",
    content: "Hello, how can I help you?",
    isUser: false,
  ),
  ChatMessage(
    id: "",
    audio: "",
    audioUrl: "http://10.128.65.249:3001/audio",
    chatId: "",
    createdAt: "",
    updatedAt: "",
    content: "I need help with my work",
    isUser: true,
  ),
  ChatMessage(
    id: "",
    audio: "",
    audioUrl: "http://10.128.65.249:3001/audio",
    chatId: "",
    createdAt: "",
    updatedAt: "",
    content: "Sure, what do you need help with?",
    isUser: false,
  ),
  ChatMessage(
    id: "",
    audio: "",
    audioUrl: "http://10.128.65.249:3001/audio",
    chatId: "",
    createdAt: "",
    updatedAt: "",
    content: "I need help with my work",
    isUser: true,
  ),
  ChatMessage(
    id: "",
    audio: "",
    audioUrl: "http://10.128.65.249:3001/audio",
    chatId: "",
    createdAt: "",
    updatedAt: "",
    content: "Sure, what do you need help with?",
    isUser: false,
  ),
  ChatMessage(
    id: "",
    audio: "",
    audioUrl: "http://10.128.65.249:3001/audio",
    chatId: "",
    createdAt: "",
    updatedAt: "",
    content: "I need help with my work",
    isUser: true,
  ),
  ChatMessage(
    id: "",
    audio: "",
    audioUrl: "http://10.128.65.249:3001/audio",
    chatId: "",
    createdAt: "",
    updatedAt: "",
    content: "Sure, what do you need help with?",
    isUser: false,
  ),
  ChatMessage(
    id: "",
    audio: "",
    audioUrl: "http://10.128.65.249:3001/audio",
    chatId: "",
    createdAt: "",
    updatedAt: "",
    content: "I need help with my work",
    isUser: true,
  ),
  ChatMessage(
    id: "",
    audio: "",
    audioUrl: "http://10.128.65.249:3001/audio",
    chatId: "",
    createdAt: "",
    updatedAt: "",
    content: "Sure, what do you need help with?",
    isUser: false,
  ),
  ChatMessage(
    id: "",
    audio: "",
    audioUrl: "http://10.128.65.249:3001/audio",
    chatId: "",
    createdAt: "",
    updatedAt: "",
    content: "I need help with my work",
    isUser: true,
  ),
  ChatMessage(
    id: "",
    audio: "",
    audioUrl: "http://10.128.65.249:3001/audio",
    chatId: "",
    createdAt: "",
    updatedAt: "",
    content: "Sure, what do you need help with?",
    isUser: false,
  ),
  ChatMessage(
    id: "",
    audio: "",
    audioUrl: "http://10.128.65.249:3001/audio",
    chatId: "",
    createdAt: "",
    updatedAt: "",
    content: "I need help with my work",
    isUser: true,
  ),
  ChatMessage(
    id: "",
    audio: "",
    audioUrl: "http://10.128.65.249:3001/audio",
    chatId: "",
    createdAt: "",
    updatedAt: "",
    content: "Sure, what do you need help with?",
    isUser: false,
  ),
  ChatMessage(
    id: "",
    audio: "",
    audioUrl: "http://10.128.65.249:3001/audio",
    chatId: "",
    createdAt: "",
    updatedAt: "",
    content: "I need help with my work",
    isUser: true,
  ),
  ChatMessage(
    id: "",
    audio: "",
    audioUrl: "http://10.128.65.249:3001/audio",
    chatId: "",
    createdAt: "",
    updatedAt: "",
    content: "Sure, what do you need help with?",
    isUser: false,
  ),
  ChatMessage(
    id: "",
    audio: "",
    audioUrl: "http://10.128.65.249:3001/audio",
    chatId: "",
    createdAt: "",
    updatedAt: "",
    content: "I need help with my work",
    isUser: true,
  ),
  ChatMessage(
    id: "",
    audio: "",
    audioUrl: "http://10.128.65.249:3001/audio",
    chatId: "",
    createdAt: "",
    updatedAt: "",
    content: "Sure, what do you need help with?",
    isUser: false,
  ),
  ChatMessage(
    id: "",
    audio: "",
    audioUrl: "http://10.128.65.249:3001/audio",
    chatId: "",
    createdAt: "",
    updatedAt: "",
    content: "I need help with my work",
    isUser: true,
  ),
  ChatMessage(
    id: "",
    audio: "",
    audioUrl: "http://10.128.65.249:3001/audio",
    chatId: "",
    createdAt: "",
    updatedAt: "",
    content: "Sure, what do you need help with?",
    isUser: false,
  ),
  ChatMessage(
    id: "",
    audio: "",
    audioUrl: "http://10.128.65.249:3001/audio",
    chatId: "",
    createdAt: "",
    updatedAt: "",
    content: "I need help with my work",
    isUser: true,
  ),
  ChatMessage(
    id: "",
    audio: "",
    audioUrl: "http://10.128.65.249:3001/audio",
    chatId: "",
    createdAt: "",
    updatedAt: "",
    content: "Sure, what do you need help with?",
    isUser: false,
  ),
];
