name: cognivoice
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  record: ^4.4.4
  audioplayers: ^5.1.0 # ^4.1.0
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.3.7
  http: ^1.1.0 # ^0.13.6
  loggerw: ^1.0.7
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  test: ^1.24.3

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/logo.png
    - assets/logo/logo.png
    - assets/icons/markettracker.png
    - assets/icons/salestracker.png
    - assets/audio-file.flac

  fonts:
    - family: IBMPlexSans
    - fonts:
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-Light.ttf
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-Regular.ttf
        - weight: 400

flutter_native_splash:
  color: "#161616"
  image: assets/logo/logo.png
  image_package: assets
  android: true
  ios: true
  fill: true
  fullscreen: false
  image_size: "center"
  android_12:
    image: assets/logo/logo.png
    image_dark: assets/logo/logo.png
    icon_background_color_dark: "#161616"
